#################### ดาวน์โหลด ########################
***Keywords***
Go to Download page
    Click link                          https://www.cpe.eng.rmutp.ac.th/download/
เริ่มทำการตรวจสอบข้อมูลหน้าดาวน์โหลด
    Scroll Element Into View            xpath=//*[contains(@class, 'entry-header')]//*[text() = 'ดาวน์โหลด']
วศ.01 แบบขอสอบหัวข้อปริญญานิพนธ์ : docx
    Click link                          http://www.cpe.eng.rmutp.ac.th/docs/en01.docx
    Go to                               chrome://downloads/
    Scroll Element Into View            xpath=//*[contains(@href,'https://www.cpe.eng.rmutp.ac.th/docs/en01.docx')]
วศ.01 แบบขอสอบหัวข้อปริญญานิพนธ์ : doc
    Click link                          http://www.cpe.eng.rmutp.ac.th/docs/en01.doc
    Go to                               chrome://downloads/
    Scroll Element Into View            xpath=//*[contains(@href,'https://www.cpe.eng.rmutp.ac.th/docs/en01.doc')]
วศ.01 แบบขอสอบหัวข้อปริญญานิพนธ์ : PDF
    Click link                          http://www.cpe.eng.rmutp.ac.th/docs/en01.pdf
    Get Window Handles                  @{Window1}
    Switch Window                       @{Window1}
วศ.02 แบบรายงานความก้าวหน้าการดำเนินงานโครงงาน : docx
    Click link                          http://www.cpe.eng.rmutp.ac.th/docs/en02.docx
    Go to                               chrome://downloads/
    Scroll Element Into View            xpath=//*[contains(@href,'https://www.cpe.eng.rmutp.ac.th/docs/en02.docx')]
วศ.02 แบบรายงานความก้าวหน้าการดำเนินงานโครงงาน : doc
    Click link                          http://www.cpe.eng.rmutp.ac.th/docs/en02.doc
    Go to                               chrome://downloads/
    Scroll Element Into View            xpath=//*[contains(@href,'https://www.cpe.eng.rmutp.ac.th/docs/en02.doc')]
วศ.02 แบบรายงานความก้าวหน้าการดำเนินงานโครงงาน : PDF
    Click link                          http://www.cpe.eng.rmutp.ac.th/docs/en02.pdf
    Get Window Handles                  @{Window1}
    Switch Window                       @{Window1}
วศ.03 แบบขอสอบปริญญานิพนธ์ : docx
    Click link                          http://www.cpe.eng.rmutp.ac.th/docs/en03.docx
    Go to                               chrome://downloads/
    Scroll Element Into View            xpath=//*[contains(@href,'https://www.cpe.eng.rmutp.ac.th/docs/en03.docx')]
วศ.03 แบบขอสอบปริญญานิพนธ์ : doc
    Click link                          http://www.cpe.eng.rmutp.ac.th/docs/en03.doc
    Go to                               chrome://downloads/
    Scroll Element Into View            xpath=//*[contains(@href,'https://www.cpe.eng.rmutp.ac.th/docs/en03.doc')]
วศ.03 แบบขอสอบปริญญานิพนธ์ : PDF
    Click link                          http://www.cpe.eng.rmutp.ac.th/docs/en03.pdf
    Get Window Handles                  @{Window1}
    Switch Window                       @{Window1}
คู่มือการดำเนินงานและจัดพิมพ์ปริญญานิพนธ์ : PDF
    Click link                          http://www.cpe.eng.rmutp.ac.th/docs/manual_project2555.pdf
    Get Window Handles                  @{Window1}
    Switch Window                       @{Window1}
วิชาโครงงาน-ลักษณะวิชา-ใบประเมิน ทั่วไป : PDF
    Click link                          http://www.cpe.eng.rmutp.ac.th/wp-content/uploads/2015/09/วิชาโครงงาน-ลักษณะวิชา-ใบประเมิน-ทั่วไป.pdf
    Scroll Element Into View            xpath=//*[contains(@href,'http://www.cpe.eng.rmutp.ac.th/wp-content/uploads/2015/09/วิชาโครงงาน-ลักษณะวิชา-ใบประเมิน-ทั่วไป.pdf')]
    Get Window Handles                  @{Window1}
    Switch Window                       @{Window1}
แบบฟอร์มเสนอโครงงานปริญญานิพนธ์ : docx
    Click link                          http://www.cpe.eng.rmutp.ac.th/docs/proposal.docx
    Go to                               chrome://downloads/
    Scroll Element Into View            xpath=//*[contains(@href,'http://www.cpe.eng.rmutp.ac.th/docs/proposal.docx')]
แบบฟอร์มเสนอโครงงานปริญญานิพนธ์ : doc
    Click link                          http://www.cpe.eng.rmutp.ac.th/docs/proposal.docx
    Go to                               chrome://downloads/
    Scroll Element Into View            xpath=//*[contains(@href,'http://www.cpe.eng.rmutp.ac.th/docs/proposal.doc')]
***Variables***
@{Window1}
    
